plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.app.chao.chaoapp'
    compileSdk = 37
    defaultConfig {
        applicationId = 'com.app.chao.chaoapp'
        minSdk = 23
        targetSdk = 37
        versionCode = 1
        versionName = '1.0'
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner = 'androidx.test.runner.AndroidJUnitRunner'
    }
    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    lint {
        checkReleaseBuilds = false
        abortOnError = false
        disable += 'NotificationPermission'
    }
    buildFeatures {
        buildConfig = true
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.13.2'
//    androidTestCompile('androidx.test.espresso:espresso-core:3.1.0', {
//        exclude group: 'com.android.support', module: 'support-annotations'
//    })
    //compile 'com.android.support:support-v4:+'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    //compile 'com.android.support.constraint:constraint-layout:1.0.2'
    //testCompile 'junit:junit:4.12'
    implementation 'io.reactivex.rxjava3:rxjava:3.1.12'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.okhttp3:okhttp:5.5.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava3:3.0.0'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.viewpager2:viewpager2:1.1.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.2.0'
    implementation 'com.github.bumptech.glide:glide:5.0.5'
    //compile 'fm.jiecao:jiecaovideoplayer:4.7.1_preview'

    //compile 'fm.jiecao:jiecaovideoplayer:4.8.3'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-java:v12.1.0'
    implementation 'com.github.CarGuo.GSYVideoPlayer:gsyvideoplayer-exo2:v12.1.0'
}
